version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
     dependencies:
        dependency-type: "production"
        patterns:
          - "*"
     dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        exclude-patterns:
          - "eslint"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
     dependencies:
        patterns:
          - "*"
